### ISSUE TITLE
Parameterise the command-line arguments container

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#10]
The `adventure.loop` function unconditionally reads command-line arguments from `sys.argv` (via the default behaviour of `argparse.ArgumentParser.parse_args`).

This makes it more difficult to treat the `loop` function as a testable function.

Please allow this dependency to be explicitly provided to the function, via an `argv` parameter that is then used as the command-line arguments list.

**Comment by bignose-debian** [comment]
At https://notabug.org/bignose/python-adventure/commits/feature/wip/stand-alone-program (specifically https://notabug.org/bignose/python-adventure/commit/29f12c6d3312dee616c9a08178954e90501538a9) is my suggested set of changes to address this.

**Comment by brandon-rhodes** [comment]
I like the idea of command line arguments being passed to the main loop, thanks! I'll get a diff up.
