### ISSUE TITLE
Obtain program's command name from command-line argument list

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#11]
When the stand-alone program has an arbitrary file name (for example, when issue #8 is accepted), the command to invoke the program may change.

The command that was _actually_ used to invoke the program is available, at index 0 of the command-line arguments.

By getting `argv[0]` as the command name, this can then be provided to the `argparse.ArgumentParser` instance as its `prog` parameter, and hence have the correct command name appear in the parser's output messages.

**Comment by bignose-debian** [comment]
At https://notabug.org/bignose/python-adventure/src/feature/wip/stand-alone-program (specifically https://notabug.org/bignose/python-adventure/commit/aeea04784dbadc4161856a52baefbce0ebc9abd5) is my suggested change to address this.

**Comment by brandon-rhodes** [comment]
See #8.
