### ISSUE TITLE
Move one-time setup out of ‘loop’ function

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#12]
The `adventure.loop` could be a proper Read-Eval-Print Loop for the program, by refactoring the one-time setup out of that function.

Please refactor the `adventure.__main__` module so that `loop` reduces to a function that takes a single parameter, the already-initialised `Game` instance, and just plays the game on that instance.

**Comment by bignose-debian** [comment]
At https://notabug.org/bignose/python-adventure/commits/feature/wip/stand-alone-program (specifically, https://notabug.org/bignose/python-adventure/commit/4b500b35c64e3a2e145d1fd68cebf26a300caa44) is my suggested set of changes to implement this.

**Comment by brandon-rhodes** [comment]
I'm at this point not inclined to split this into two functions as I don't quite see the utility. For now I'm going to close this issue. Thanks for the idea, though!
