### ISSUE TITLE
Add original documentation for data file parser

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#13]
The data file format is described in specific detail in the original Fortran code.

We can take those original comments and turn them into a docstring on the handler for each section.

**Comment by bignose-debian** [comment]
At https://notabug.org/bignose/python-adventure/commit/ae6f3c4e1d327d42190de92bfcdf7a78240120d1 is my suggested change to add this documentation.

**Comment by brandon-rhodes** [comment]
Good idea! I've accepted the patch, though I'll remove the `coding:` line as it's not needed in Python 3. Thanks!
