### ISSUE TITLE
Include non-program source files in the source distribution

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#14]
The source distribution created by Distutils has some useful defaults for which files to include. These are not perfect, however, and should be customised by a `MANIFEST` document.

The `MANIFEST` document can be generated by Distutils at build time, from a `MANIFEST.in` template. See the [`MANIFEST.in` section of the Python Packaging User Guide](https://packaging.python.org/en/latest/distributing/#manifest-in).

Please add a `MANIFEST.in` template to specify explicitly which non-program files to include in the generated source distribution.

**Comment by bignose-debian** [comment]
I suggest the change set at <https://notabug.org/bignose/python-adventure/commit/64ad5cf13fa9ebf4df4da3fa80a9870ed078dd3b> to address this.

**Comment by brandon-rhodes** [comment]
Thanks for the idea of including the LICENSE in the distribution! Fixed.
