### ISSUE TITLE
Add a Unix manual page for the stand-alone program

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#15]
The program invoked to run the game (with the name `colossal-cave-adventure`, for example) should have a Unix manual page describing what the program is.

This allows someone whose only interface to the program is that command, to get information from a standard location about the program and its significance.

Please add a Unix manual page for `colossal-cave-adventure` as user documentation.

**Comment by bignose-debian** [comment]
I have written a Unix manual page (in the manual section 6, for games). The change set at <https://notabug.org/bignose/python-adventure/commit/21bfddb2c421ac2dcbf1c4c4d02d3234717cf620> adds this to the distribution.

**Comment by brandon-rhodes** [comment]
Thanks for the manual page! I am not inclined, though, to suit up this Python port as though it’s the real program; I hope that a Linux or Unix administrator will only be installing the real C program system-wide for users who simply want to play. This, I would imagine, would be played by a Python programmer with a local pip install, which do not incur man pages. So let’s leave the manual page over in your branch for folks who need it, but not bring it into the main repository.
