### ISSUE TITLE
Set terminal to upper case while program is running

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#16]
For greater verisimilitude with the original ADVENT, the command-line program could set the terminal attributes to force all text to upper case while the program runs.

This would mean the user's own typed text, while it is received in the program however the user types it, would appear on the terminal in upper case.

**Comment by bignose-debian** [comment]
My suggested implementation of this uses the standard library `termios` module to set the terminal attributes to force upper case, and restore them when the game is done.

See the branch at https://notabug.org/bignose/python-adventure/src/wip/feature/terminal-uppercase which adds a module (and its unit tests) to implement this functionality.

**Comment by bignose-debian** [comment]
The “stand-alone program” branch goes well with this IMO, so I have made an alternative branch https://notabug.org/bignose/python-adventure/src/wip/feature/stand-alone-program-uppercase to add this feature on the stand-alone program.

**Comment by bignose-debian** [comment]
Bah, this is too flaky to work correctly: it results in garbage on the screen where control sequences should occur. The above changes should not be applied.

The OLCUC feature is poorly implemented, and is even marked “LEGACY” by [the Single Unix Specification for termios](http://pubs.opengroup.org/onlinepubs/7908799/xbd/termios.html).

I advise seeking a different (maybe Python-specific) solution for displaying input echo as upper case.

**Comment by brandon-rhodes** [comment]
Thank you for the research into this possible feature, I had no idea that the Linux terminal would not handle all-caps more smoothly than apparently it does! I am going to close this issue for now, since otherwise we would probably need to patch readline which does not sound like much fun. Feel free to re-open if you ever find an easy solution, though!
