### ISSUE TITLE
Maintain separate change log document

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#17]
The change log is currently tacked onto the end of the README document, down in the Python module. I think the information deserves a top-level change log document.

This would also allow expanding the format of the log: a separate section for each version, specifying release date and maintainer, with a bullet list of user-visible changes in each version.

**Comment by bignose-debian** [comment]
My suggested implementation is a top-level `CHANGES.txt` document in reStructuredText format. This allows metadata for each version such as release date, to be specified in a field list for the version.

The branch at https://notabug.org/bignose/python-adventure/src/wip/feature/changelog-document also has a section for the in-progress version, to allow changes to be documented before the release date or version number is known.

**Comment by brandon-rhodes** [comment]
My suspicion is that `python-adventure`, as a feature-complete port of the original, will not be seeing further versions released. For now, let’s keep the change log inline where it’s easier for folks to read right in the main documentation file. If in the future it becomes clear that Adventure is going back into an active development phase, then we can re-open this and opt for the more complicated but flexible scheme where the changelog is a separate file. Thanks!
