### ISSUE TITLE
Tags from Bitbucket repository

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#2]
Please add to this repository the tags that were in the Mercurial repository at Bitbucket.

**Comment by brandon-rhodes** [comment]
The tags went away! I had not noticed that. I have gone in and added them back by hand. Thanks for noticing so that I could get them restored!

**Comment by bignose-debian** [comment]
Thanks for attending to this.

The resulting commits now look strange. Mercurial's weird insistence on a separate commit to merely add a tag, means you now have some commits that claim to add a tag but don't; and the ones which do, claim a different hash in the commit message.

    […]
    4d6c2289 * 1.3 Added tag 1.3 for changeset 7059f3f9f166
    ff7e2551 * Added tag 1.3 for changeset bb64adc9cd14
    […]
    5f49f179 * 1.1 Added tag 1.1 for changeset 3aa4ba805e55
    4762f669 * Updated version number and released.
    5511c3aa * Added tag 1.1 for changeset be26fdf30b49
    […]

Don't know whether that's worth fixing, by removing the “added a tag” commits and just applying the tags to the actual code-changing commits.

**Comment by brandon-rhodes** [comment]
Removing the commits would re-hash all subsequent history and invalidate all checked out, and all forked, versions of the repository, so I am inclined to leave things as they are — it would look even more wrong, at least to my eyes, if the "1.3" tag were on something earlier than the very last mention of 1.3 in the history. Thanks for pointing out the awkwardness, though — I had not noticed it myself yet after the transition, and would have been confused!
