### ISSUE TITLE
Migrate VCS ignore patterns to Git

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#3]
Please migrate to a Git ignore file, and drop the unused Mercurial ignore file.

**Comment by bignose-debian** [comment]
See the [‘vcs-ignore’ branch](https://notabug.org/bignose/python-adventure/commits/vcs-ignore) for my suggested fix for this issue.

**Comment by brandon-rhodes** [comment]
I have merged in your contribution. Thanks!
