### ISSUE TITLE
Use ‘cmd’ module to provide interactive command line

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#5]
Would it be against the intent of this package, to improve the interactive command interface?

Python's standard library [`cmd` module](https://docs.python.org/3/library/cmd.html) provides a much nicer interactive command line than the basic `input` function.

But perhaps the intent of this code is to mimic as closely as possible the limited features of the original. I'd love to know which is the case.

**Comment by brandon-rhodes** [comment]
What specific feature are you wishing that the command line provided? If you want command line interaction, then I suspect it is really the `readline` library that you are missing, which I can fix by adding a quick `import readline` to the `__main__.py` file. Let me know and I will try to get the situation improved for you!

**Comment by brandon-rhodes** [comment]
I have made the `readline` import in a160e41, so I am going to provisionally close this bug — but please feel free to re-open it if you had further features in mind besides command-line editing. Thanks!
