### ISSUE TITLE
Allow import of ‘adventure.__main__’ module

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#7]
The `adventure.__main__` module cannot be safely imported; it goes ahead and begins the game loop.

This behaviour foils the ability to unit-test the code in that module. It also prevents setting an “entry point” to import, then run a function.

Please move the top-level main-line code to a `if __name__ == '__main__'` block.

**Comment by bignose-debian** [comment]
At https://notabug.org/bignose/python-adventure/src/feature/wip/stand-alone-program (specifically, https://notabug.org/bignose/python-adventure/commit/9fb12a445847c8d8e27688052771e965378770cf) is my suggested change to address this.

**Comment by brandon-rhodes** [comment]
Neat! I had not fully realized that, because module names are fully qualified, even a module name `__main__.py` does *not* have a `__name__` of `__main__` when simply imported as part of its package, but instead is named `adventure.__main__`.
