### ISSUE TITLE
Move main-line exception handling to custom ‘main’ function

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#9]
The `adventure.__main__` module has top-level code which catches any `EOFError` and simply discards it (with a `pass` statement).

```
try:
    loop()
except EOFError:
    pass
```

What is the purpose of that? Is there any condition where `EOFError` is not a bug; and if so, why not handle that condition specifically?

**Comment by bignose-debian** [comment]
Assuming this is a superfluous interception of the exception, I have removed it in https://notabug.org/bignose/python-adventure/commits/feature/wip/stand-alone-program (specifically https://notabug.org/bignose/python-adventure/commit/f67f4bb94f2102651254cb378faefc3230350bd2).

**Comment by bignose-debian** [comment]
On the other hand, if this is to handle a user-requested program exit, I think this is better in an explicit conventional ‘main’ function that can perform exception handling and return a program exit status to the caller.

See https://notabug.org/bignose/python-adventure/commit/741c6bbfc7370eec5f33cb4ebefb591b26289ac6 for my suggested change to implement this.

**Comment by brandon-rhodes** [comment]
The exception handler targets the common case of a Unix programmer exiting a program by sending it end-of-file with Control-D. I'm going to leave it as-is for the moment.
